version: '3.4'
services:
  web:
    build: .
    environment:
      NODE_ENV: '${NODE_ENV}'
      JWT_SEED: '${JWT_SEED}'
      JWT_EXPIRES_IN: '${JWT_EXPIRES_IN}'
    ports:
      - '8080:8080'
    volumes:
      - .:/app
